name: run script

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  first_jobs:
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: run script
        run: |
          chmod +x script.sh
          ./script.sh

      - name: run name
        run: |
          echo "my name is ${{ vars.NAME }}"
